import { NextRequest, NextResponse } from "next/server"
import { adminAuth, isAdminConfigured } from "@/lib/firebase-admin"
import { sendPasswordResetEmail } from "@/lib/mail"

export async function POST(request: NextRequest) {
  if (!isAdminConfigured || !adminAuth) {
    return NextResponse.json(
      { error: "Serviço de e-mail não configurado." },
      { status: 503 }
    )
  }

  const { email } = await request.json()

  if (!email || typeof email !== "string") {
    return NextResponse.json(
      { error: "E-mail é obrigatório." },
      { status: 400 }
    )
  }

  try {
    const projectUrl = process.env.PROJECT_URL
    if (!projectUrl) {
      return NextResponse.json(
        { error: "URL do projeto não configurada." },
        { status: 503 }
      )
    }

    const link = await adminAuth.generatePasswordResetLink(email, {
      url: `${projectUrl}/redefinir-senha`,
      handleCodeInApp: false,
    })

    // The link generated by Firebase contains the oobCode as a query param.
    // We rewrite it so the user lands on our own UI instead of Firebase's.
    const url = new URL(link)
    const oobCode = url.searchParams.get("oobCode")

    const resetUrl = `${projectUrl}/redefinir-senha?oobCode=${encodeURIComponent(oobCode!)}`

    await sendPasswordResetEmail(email, resetUrl)

    return NextResponse.json({ message: "E-mail de recuperação enviado com sucesso." })
  } catch (error: unknown) {
    const firebaseError = error as { code?: string; message?: string }

    if (firebaseError.code === "auth/user-not-found") {
      return NextResponse.json(
        { error: "E-mail não encontrado." },
        { status: 404 }
      )
    }

    console.error("Erro ao gerar link de reset:", firebaseError.code, firebaseError.message)

    const msg = (firebaseError.message || "").includes("RESET_PASSWORD_EXCEED_LIMIT")
      ? "Muitas tentativas. Aguarde alguns minutos e tente novamente."
      : "Erro ao processar solicitação."

    return NextResponse.json(
        //debug info is included in the response for easier troubleshooting, but it should be ignored by the client
      { error: msg, _debug: { code: firebaseError.code, message: firebaseError.message } },
      { status: 500 }
    )
  }
}
